### ISSUE TITLE
README has the wrong picture for 8 of Clubs

### ISSUE THREAD

**Issue by ananthamapod** [Bathlamos/Programmers-Playing-Cards#21]
Based on the code in the Clubs folder, this should be C++, not Coffeescript

![image](https://cloud.githubusercontent.com/assets/5254722/16365019/90e19ed6-3bc2-11e6-934f-cf4edc3b0a7e.png)

**Comment by Bathlamos** [comment]
Hi there! You're right, I made a mistake there, as I update these images quite often. It should display the correct card at present.

Thank you for bringing this issue to my attention :)
