### ISSUE TITLE
Queston regarding maximum LOC for Example Code

### ISSUE THREAD

**Issue by nycjv321** [Bathlamos/Programmers-Playing-Cards#22]
What is the maximum number of lines that a code example can be? Some languages are naturally more "verbose" than others. I am looking at the Java example and would like to provide a more cleanly implemented class definition, but am finding myself writing > 9 lines.

```
public class Card {
    private final int rank;
    private final Suit suit;
    public enum Suit {DIAMONDS}
    static {
        new Card(8, Suit.DIAMONDS);
    }
    public Card(int rank, Suit suit) {
        this.rank = rank;
        this.suit = suit;
    }
}

```

 What is the maximum number of lines that will be accepted?

**Comment by Bathlamos** [comment]
Hi there!

I agree that the Java example is particularly bad in terms of code omitted (or implied). 

Keep in mind that the code can be a maximum of 24 characters wide and 8 lines long. For instance, I totally agree that the class variables should be final and private, but that's pretty long already. If you can modify the code to fit in the required space, I'm definitely down to swap it with what we have at present! What do you think?

**Comment by nycjv321** [comment]
This is what I could come up with:

```
public enum Card {
 THIS(8, DIAMONDS);
 int rank; Suit suit;
 Card(int rank,
      Suit suit) {
  this.rank = rank;
  this.suit = suit;}
} enum Suit {DIAMONDS}
```

Thoughts?

**Comment by Bathlamos** [comment]
I agree that your code is more accurate, however it is also too dense to be easily readable on a card. For now, we will keep the current code. 

I'm closing the issue, but feel free to reopen it if you can streamline the Java code a bit more. Thank you again so much for your contribution!
