### ISSUE TITLE
4 of Hearts

### ISSUE THREAD

**Issue by Hbrinj** [Bathlamos/Programmers-Playing-Cards#24]
I'm not sure how Haskelly the example is, I've come up with a new one but it's possibly a bit longer but i feel that you should show currying in the little example :) What are the constraints we're working towards? what are your views on what can be left out?

``` Haskell
type Suit = String
type Rank = Int

data Card = Card{
  rank :: Rank,
  suit :: Suit }
  deriving(Show)

newCard :: Rank -> Suit -> Card
newCard = \r -> \s ->
    Card{ rank = r, suit = s }

card :: Card
card = newCard 4 "Hearts"
```

**Comment by Bathlamos** [comment]
Hi there! Thank you for addressing some of the shortcomings of the cards.

I agree that including as many aspects of the languages is a must. The main constraint is the size of the cards. Our snippet of code cannot be more than 24 characters wide and 8 lines long.

Do you think that you can edit the snippet above to fit these constraints? Either by removing unimportant aspects of the code or changing the logic altogether? I'm simply not knowledgeable enough in Haskell to suggest what to keep or change.

**Comment by Hbrinj** [comment]
I'll keep thinking about it but for the mean time I'll put a pr in for the current snippet as I will technically error if the card data doesn't derive show

**Comment by Hbrinj** [comment]
Closed for now, until i can think of some magic :)
