### ISSUE TITLE
PHP and HAXE

### ISSUE THREAD

**Issue by mrlilly** [Bathlamos/Programmers-Playing-Cards#8]
I think pho and haze need looking at as I do not believe they are correct

**Comment by mrlilly** [comment]
Sorry, should say PHP

**Comment by mrlilly** [comment]
Sorry, the haxe code looks okay in the code snippet, it is the picture that is incorrect. PHP is wrong on image also.

**Comment by Bathlamos** [comment]
Thank you very much for bringing this up. It's absolutely crucial that the code on the images reflect the code on Github
